name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: The type of release.
        type: choice
        options:
          - proto
          - generator
          - all
        default: all
      version_type:
        description: The version type to bump.
        type: choice
        options:
          - patch
          - minor
          - major
        default: minor

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise run lint

  release_proto:
    name: Release Proto
    runs-on: ubuntu-latest
    if: ${{ inputs.type == 'proto' || inputs.type == 'all' }}
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Mise
        uses: jdx/mise-action@v3
      - name: Push
        uses: bufbuild/buf-push-action@v1
        with:
          input: proto/oapi/v1
          buf_token: ${{ secrets.BUF_TOKEN_NEW }}

  release_generator:
    name: Release Generator
    runs-on: ubuntu-latest
    if: ${{ inputs.type == 'generator' || inputs.type == 'all' }}
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Mise
        uses: jdx/mise-action@v3
      - name: Get version
        id: get_version
        run: |
          version=$(git describe --abbrev=0 --match "v*.*.*" || echo "v0.1.0")
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Next Version
        uses: dotjoshrc/next-version-action@v1
        id: version
        with:
          version: ${{ steps.get_version.outputs.version }}
          type: ${{ inputs.version_type }}
      - name: Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.next_version }}
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Rollback
        if: failure()
        run: git push --delete origin ${{ steps.version.outputs.next_version }}
